# Generated by Django 6.0 on 2026-02-03 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=100, null=True, verbose_name='کوپن تخفیف')),
                ('discount', models.IntegerField(default=0, verbose_name='درصد تخفیف')),
                ('start_date', models.DateTimeField(verbose_name='تاریخ شروع تخفیف')),
                ('end_date', models.DateTimeField(verbose_name='تاریخ پایان تخفیف')),
                ('active', models.BooleanField(default=False, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'کوپن تخفیف',
                'verbose_name_plural': ' کوپن های تخفیف',
            },
        ),
    ]
