# Generated by Django 6.0 on 2026-02-03 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True, null=True, verbose_name='ادرس')),
                ('tel', models.CharField(blank=True, max_length=11, null=True, verbose_name='تلفن')),
                ('date_birthday', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تولد')),
                ('img_profile', models.ImageField(default='professional-img.png', upload_to='profile', verbose_name='عکس کاربر')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پروفایل',
                'verbose_name_plural': ' پروفایل ها',
            },
        ),
    ]
