# Generated by Django 5.2.17 on 2026-09-02 07:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titer', models.CharField(max_length=50, verbose_name='تیتر خبر ')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, unique=True)),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد')),
                ('update_date', models.DateTimeField(auto_now=True, null=True, verbose_name='تاریخ ویرایش')),
            ],
            options={
                'verbose_name': 'عنوان خبر',
                'verbose_name_plural': ' عنوان اخبار',
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام قطعه')),
                ('price', models.PositiveIntegerField(verbose_name='هزینه')),
            ],
            options={
                'verbose_name': 'قطعه',
                'verbose_name_plural': 'قطعات',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='services', verbose_name='ایکون سرویس')),
                ('img', models.ImageField(blank=True, null=True, upload_to='services', verbose_name='تصویر سرویس')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد')),
                ('update_date', models.DateTimeField(auto_now=True, null=True, verbose_name='تاریخ ویرایش')),
            ],
            options={
                'verbose_name': 'خدمت',
                'verbose_name_plural': ' خدمات',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cname', models.CharField(max_length=100, verbose_name='نام و نام خانوادگی مشتری')),
                ('tel', models.CharField(max_length=11, unique=True, verbose_name='شماره تماس')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'مشتری',
                'verbose_name_plural': 'مشتری ها',
            },
        ),
        migrations.CreateModel(
            name='Factor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_service', models.PositiveIntegerField(default=0, verbose_name='اجرت کل خدمات')),
                ('tax_percent', models.PositiveIntegerField(default=9, verbose_name='درصد مالیات')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('client_fact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Home.client', verbose_name='مشتری')),
                ('parts', models.ManyToManyField(blank=True, related_name='factors', to='Home.part', verbose_name='قطعات')),
                ('services', models.ManyToManyField(blank=True, related_name='factors', to='Home.services', verbose_name='خدمات')),
            ],
            options={
                'verbose_name': 'فاکتور',
                'verbose_name_plural': 'فاکتورها',
            },
        ),
        migrations.CreateModel(
            name='Sub_news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_titer', models.CharField(blank=True, max_length=50, null=True, verbose_name='عنوان')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, unique=True)),
                ('sub_summary', models.TextField(blank=True, max_length=20, null=True, verbose_name='شرح مختصر')),
                ('sub_description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('sub_create_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('sub_update_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('is_published', models.BooleanField(default=False)),
                ('reading_time', models.PositiveSmallIntegerField(default=5, verbose_name='زمان مطالعه (دقیقه)')),
                ('views', models.CharField(blank=True, null=True, verbose_name='تعداد مشاهده')),
                ('sub_img', models.ImageField(blank=True, null=True, upload_to='blog', verbose_name='تصویر سرویس')),
                ('new', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='Home.news', verbose_name='دسته بندی اخبار')),
            ],
            options={
                'verbose_name': 'دسته بندی خبر',
                'verbose_name_plural': ' دسته بندی اخبار',
            },
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(choices=[('ref and freez', 'یخچال و فریزر'), ('laundry', 'ماشین لباسشویی'), ('dishwasher', 'ماشین ظرفشویی'), ('food procs', 'غذاساز'), ('coffe maker', 'قهوه ساز'), ('others', 'سایر')], max_length=20, verbose_name='نوع دستگاه')),
                ('information', models.CharField(max_length=200, verbose_name='اطلاعات')),
                ('request_date', models.DateField(auto_now_add=True, verbose_name='تاریخ درخواست')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='Home.client', verbose_name='مشتری')),
            ],
            options={
                'verbose_name': 'درخواست سرویس',
                'verbose_name_plural': 'درخواست های سرویس',
                'constraints': [models.UniqueConstraint(fields=('client', 'request_date'), name='one_request_per_client_per_day')],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.TextField(max_length=600, verbose_name='نظر')),
                ('rating', models.PositiveSmallIntegerField(default=5, verbose_name='امتیاز')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('is_approved', models.BooleanField(default=False, verbose_name='تایید پیام')),
                ('factor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='Home.factor', verbose_name='فاکتور')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='Home.services', verbose_name='خدمت')),
            ],
            options={
                'verbose_name': 'نظر',
                'verbose_name_plural': 'نظرات',
                'constraints': [models.UniqueConstraint(fields=('factor', 'service'), name='unique_review_per_factor_service')],
            },
        ),
    ]
