# Generated by Django 5.2.17 on 2026-09-08 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factor',
            name='parts',
        ),
        migrations.RemoveField(
            model_name='factor',
            name='price_service',
        ),
        migrations.RemoveField(
            model_name='factor',
            name='services',
        ),
        migrations.CreateModel(
            name='FactorService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_service', models.PositiveIntegerField(default=0, verbose_name='اجرت خدمت')),
                ('factor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factor_services', to='Home.factor', verbose_name='فاکتور')),
                ('parts', models.ManyToManyField(blank=True, related_name='factor_services', to='Home.part', verbose_name='قطعات')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.services', verbose_name='خدمت')),
            ],
        ),
    ]
