# Generated by Django 5.2.17 on 2026-09-08 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_remove_factor_parts_remove_factor_price_service_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factorservice',
            name='parts',
        ),
        migrations.CreateModel(
            name='PartUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='تعداد')),
                ('unit_price', models.PositiveIntegerField(default=0, verbose_name='قیمت واحد')),
                ('factor_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_usages', to='Home.factorservice', verbose_name='خدمت فاکتور')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.part', verbose_name='قطعه')),
            ],
        ),
    ]
