# Generated by Django 5.2.17 on 2026-09-08 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_remove_factorservice_parts_partusage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='factorservice',
            options={'verbose_name': 'اقلام فاکتور', 'verbose_name_plural': 'اقلام فاکتورها'},
        ),
        migrations.AlterModelOptions(
            name='partusage',
            options={'verbose_name': 'تعداد قطعه', 'verbose_name_plural': 'تعداد قطعات'},
        ),
    ]
