# Generated by Django 5.2.17 on 2026-09-08 19:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_alter_factorservice_options_alter_partusage_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partusage',
            name='quantity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='تعداد'),
        ),
    ]
