# Generated by Django 5.2.17 on 2026-09-11 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0005_alter_partusage_quantity"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="news",
            options={"verbose_name": "عنوان خبر", "verbose_name_plural": "عنوان اخبار"},
        ),
        migrations.AlterModelOptions(
            name="services",
            options={"verbose_name": "خدمت", "verbose_name_plural": "خدمات"},
        ),
        migrations.AlterModelOptions(
            name="sub_news",
            options={
                "verbose_name": "دسته بندی خبر",
                "verbose_name_plural": "دسته بندی اخبار",
            },
        ),
        migrations.AddField(
            model_name="factor",
            name="is_issued",
            field=models.BooleanField(default=False, verbose_name="فاکتور صادر شده"),
        ),
        migrations.AlterField(
            model_name="news",
            name="titer",
            field=models.CharField(max_length=50, verbose_name="تیتر خبر"),
        ),
        migrations.AlterField(
            model_name="services",
            name="icon",
            field=models.ImageField(
                blank=True, null=True, upload_to="services", verbose_name="آیکون سرویس"
            ),
        ),
    ]
