# Generated by Django 5.2.17 on 2026-09-21 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_seed_articles'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='icon_hover',
            field=models.ImageField(blank=True, null=True, upload_to='services', verbose_name='آیکون هاور سرویس'),
        ),
        migrations.CreateModel(
            name='ServiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان خدمت')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Home.services', verbose_name='سرویس')),
            ],
            options={
                'verbose_name': 'مورد خدمت',
                'verbose_name_plural': 'موارد خدمات',
            },
        ),
    ]
