# Generated by Django 5.2.17 on 2026-09-25 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0011_remove_article_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceitem',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_items', to='Home.services', verbose_name='سرویس'),
        ),
        migrations.AlterField(
            model_name='sub_news',
            name='sub_summary',
            field=models.TextField(blank=True, max_length=50, null=True, verbose_name='شرح مختصر'),
        ),
        migrations.AlterField(
            model_name='sub_news',
            name='sub_titer',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='عنوان'),
        ),
    ]
