# Generated by Django 5.2.17 on 2026-09-25 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0012_alter_serviceitem_service_alter_sub_news_sub_summary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_news',
            name='sub_titer',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='عنوان'),
        ),
    ]
